name = input('what is your name:?')
age =input('how old are you:?')
city = input('where do you live exaactly:?')
print('welcome',name,'in jordan:')
profession = input('what is your business:?')
print('name:',name,'age:',age,'city:',city,'profession:',profession)
